development:
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: postgres
  database: zero_tpl_dev
test:
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: postgres
  database: zero_tpl_test
production:
  url: <%= ENV['TPL_DATABASE_URL'] %>
